require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlogCategoriesController do

  # This should return the minimal set of attributes required to create a valid
  # BlogCategory. As you add validations to BlogCategory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlogCategoriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  # User has to be logged in as admin
  before do
    ApplicationController.any_instance.stub(:authorize_admin!).and_return(true)
  end

  describe "GET index" do
    it "assigns all blog_categories as @blog_categories" do
      blog_category = BlogCategory.create! valid_attributes
      get :index, {}, valid_session
      assigns(:blog_categories).should eq([blog_category])
    end
  end

  describe "GET show" do
    it "assigns the requested blog_category as @blog_category" do
      blog_category = BlogCategory.create! valid_attributes
      get :show, {:id => blog_category.to_param}, valid_session
      assigns(:blog_category).should eq(blog_category)
    end
  end

  describe "GET new" do
    it "assigns a new blog_category as @blog_category" do
      get :new, {}, valid_session
      assigns(:blog_category).should be_a_new(BlogCategory)
    end
  end

  describe "GET edit" do
    it "assigns the requested blog_category as @blog_category" do
      blog_category = BlogCategory.create! valid_attributes
      get :edit, {:id => blog_category.to_param}, valid_session
      assigns(:blog_category).should eq(blog_category)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BlogCategory" do
        expect {
          post :create, {:blog_category => valid_attributes}, valid_session
        }.to change(BlogCategory, :count).by(1)
      end

      it "assigns a newly created blog_category as @blog_category" do
        post :create, {:blog_category => valid_attributes}, valid_session
        assigns(:blog_category).should be_a(BlogCategory)
        assigns(:blog_category).should be_persisted
      end

      it "redirects to the created blog_category" do
        post :create, {:blog_category => valid_attributes}, valid_session
        response.should redirect_to(BlogCategory.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved blog_category as @blog_category" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlogCategory.any_instance.stub(:save).and_return(false)
        post :create, {:blog_category => { "name" => "invalid value" }}, valid_session
        assigns(:blog_category).should be_a_new(BlogCategory)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlogCategory.any_instance.stub(:save).and_return(false)
        post :create, {:blog_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested blog_category" do
        blog_category = BlogCategory.create! valid_attributes
        # Assuming there are no other blog_categories in the database, this
        # specifies that the BlogCategory created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BlogCategory.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => blog_category.to_param, :blog_category => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested blog_category as @blog_category" do
        blog_category = BlogCategory.create! valid_attributes
        put :update, {:id => blog_category.to_param, :blog_category => valid_attributes}, valid_session
        assigns(:blog_category).should eq(blog_category)
      end

      it "redirects to the blog_category" do
        blog_category = BlogCategory.create! valid_attributes
        put :update, {:id => blog_category.to_param, :blog_category => valid_attributes}, valid_session
        response.should redirect_to(blog_category)
      end
    end

    describe "with invalid params" do
      it "assigns the blog_category as @blog_category" do
        blog_category = BlogCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlogCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => blog_category.to_param, :blog_category => { "name" => "invalid value" }}, valid_session
        assigns(:blog_category).should eq(blog_category)
      end

      it "re-renders the 'edit' template" do
        blog_category = BlogCategory.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlogCategory.any_instance.stub(:save).and_return(false)
        put :update, {:id => blog_category.to_param, :blog_category => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested blog_category" do
      blog_category = BlogCategory.create! valid_attributes
      expect {
        delete :destroy, {:id => blog_category.to_param}, valid_session
      }.to change(BlogCategory, :count).by(-1)
    end

    it "redirects to the blog_categories list" do
      blog_category = BlogCategory.create! valid_attributes
      delete :destroy, {:id => blog_category.to_param}, valid_session
      response.should redirect_to(blog_categories_url)
    end
  end

end
