# require 'spec_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to specify the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator.  If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails.  There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.
# #
# # Compared to earlier versions of this generator, there is very limited use of
# # stubs and message expectations in this spec.  Stubs are only used when there
# # is no simpler way to get a handle on the object needed for the example.
# # Message expectations are only used when there is no simpler way to specify
# # that an instance is receiving a specific message.

# describe VideoChatsController do

#   # This should return the minimal set of attributes required to create a valid
#   # VideoChat. As you add validations to VideoChat, be sure to
#   # update the return value of this method accordingly.
#   def valid_attributes
#     {}
#   end

#   # This should return the minimal set of values that should be in the session
#   # in order to pass any filters (e.g. authentication) defined in
#   # VideoChatsController. Be sure to keep this updated too.
#   def valid_session
#     {}
#   end

#   describe "GET index" do
#     it "assigns all video_chats as @video_chats" do
#       video_chat = VideoChat.create! valid_attributes
#       get :index, {}, valid_session
#       assigns(:video_chats).should eq([video_chat])
#     end
#   end

#   describe "GET show" do
#     it "assigns the requested video_chat as @video_chat" do
#       video_chat = VideoChat.create! valid_attributes
#       get :show, {:id => video_chat.to_param}, valid_session
#       assigns(:video_chat).should eq(video_chat)
#     end
#   end

#   describe "GET new" do
#     it "assigns a new video_chat as @video_chat" do
#       get :new, {}, valid_session
#       assigns(:video_chat).should be_a_new(VideoChat)
#     end
#   end

#   describe "GET edit" do
#     it "assigns the requested video_chat as @video_chat" do
#       video_chat = VideoChat.create! valid_attributes
#       get :edit, {:id => video_chat.to_param}, valid_session
#       assigns(:video_chat).should eq(video_chat)
#     end
#   end

#   describe "POST create" do
#     describe "with valid params" do
#       it "creates a new VideoChat" do
#         expect {
#           post :create, {:video_chat => valid_attributes}, valid_session
#         }.to change(VideoChat, :count).by(1)
#       end

#       it "assigns a newly created video_chat as @video_chat" do
#         post :create, {:video_chat => valid_attributes}, valid_session
#         assigns(:video_chat).should be_a(VideoChat)
#         assigns(:video_chat).should be_persisted
#       end

#       it "redirects to the created video_chat" do
#         post :create, {:video_chat => valid_attributes}, valid_session
#         response.should redirect_to(VideoChat.last)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns a newly created but unsaved video_chat as @video_chat" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         VideoChat.any_instance.stub(:save).and_return(false)
#         post :create, {:video_chat => {}}, valid_session
#         assigns(:video_chat).should be_a_new(VideoChat)
#       end

#       it "re-renders the 'new' template" do
#         # Trigger the behavior that occurs when invalid params are submitted
#         VideoChat.any_instance.stub(:save).and_return(false)
#         post :create, {:video_chat => {}}, valid_session
#         response.should render_template("new")
#       end
#     end
#   end

#   describe "PUT update" do
#     describe "with valid params" do
#       it "updates the requested video_chat" do
#         video_chat = VideoChat.create! valid_attributes
#         # Assuming there are no other video_chats in the database, this
#         # specifies that the VideoChat created on the previous line
#         # receives the :update_attributes message with whatever params are
#         # submitted in the request.
#         VideoChat.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
#         put :update, {:id => video_chat.to_param, :video_chat => {'these' => 'params'}}, valid_session
#       end

#       it "assigns the requested video_chat as @video_chat" do
#         video_chat = VideoChat.create! valid_attributes
#         put :update, {:id => video_chat.to_param, :video_chat => valid_attributes}, valid_session
#         assigns(:video_chat).should eq(video_chat)
#       end

#       it "redirects to the video_chat" do
#         video_chat = VideoChat.create! valid_attributes
#         put :update, {:id => video_chat.to_param, :video_chat => valid_attributes}, valid_session
#         response.should redirect_to(video_chat)
#       end
#     end

#     describe "with invalid params" do
#       it "assigns the video_chat as @video_chat" do
#         video_chat = VideoChat.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         VideoChat.any_instance.stub(:save).and_return(false)
#         put :update, {:id => video_chat.to_param, :video_chat => {}}, valid_session
#         assigns(:video_chat).should eq(video_chat)
#       end

#       it "re-renders the 'edit' template" do
#         video_chat = VideoChat.create! valid_attributes
#         # Trigger the behavior that occurs when invalid params are submitted
#         VideoChat.any_instance.stub(:save).and_return(false)
#         put :update, {:id => video_chat.to_param, :video_chat => {}}, valid_session
#         response.should render_template("edit")
#       end
#     end
#   end

#   describe "DELETE destroy" do
#     it "destroys the requested video_chat" do
#       video_chat = VideoChat.create! valid_attributes
#       expect {
#         delete :destroy, {:id => video_chat.to_param}, valid_session
#       }.to change(VideoChat, :count).by(-1)
#     end

#     it "redirects to the video_chats list" do
#       video_chat = VideoChat.create! valid_attributes
#       delete :destroy, {:id => video_chat.to_param}, valid_session
#       response.should redirect_to(video_chats_url)
#     end
#   end

# end
